<?php

namespace Proyecto\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComodinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComodinRepository extends EntityRepository
{
}
